name: dsv3 Build and Deploy pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:
    types: [tekton-trigger]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Make sure this matches your local environment

      - name: Clean install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Verify Vite installation
        run: |
          npm list vite @vitejs/plugin-react

      - name: Build project
        run: |
          npm run build

      # - name: Archive build artifacts
      #   run: |
      #     mkdir -p output
      #     cp -r dist/* output/

      # - name: Upload build artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: build-output
      #     path: output/
